from pathlib import Path
import os
import re

ANDROID_API = "36"

def patch_gradle_text(text: str) -> str:
    # Groovy DSL
    text = text.replace("compileSdkVersion flutter.compileSdkVersion", f"compileSdkVersion {ANDROID_API}")
    text = text.replace("targetSdkVersion flutter.targetSdkVersion", f"targetSdkVersion {ANDROID_API}")
    text = text.replace("compileSdk flutter.compileSdkVersion", f"compileSdk {ANDROID_API}")
    text = text.replace("targetSdk flutter.targetSdkVersion", f"targetSdk {ANDROID_API}")

    # Kotlin DSL
    text = text.replace("compileSdk = flutter.compileSdkVersion", f"compileSdk = {ANDROID_API}")
    text = text.replace("targetSdk = flutter.targetSdkVersion", f"targetSdk = {ANDROID_API}")

    # Numeric values
    text = re.sub(r"compileSdkVersion\s+\d+", f"compileSdkVersion {ANDROID_API}", text)
    text = re.sub(r"targetSdkVersion\s+\d+", f"targetSdkVersion {ANDROID_API}", text)
    text = re.sub(r"compileSdk\s*=\s*\d+", f"compileSdk = {ANDROID_API}", text)
    text = re.sub(r"targetSdk\s*=\s*\d+", f"targetSdk = {ANDROID_API}", text)
    return text

def patch_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False

    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False

    new_text = patch_gradle_text(text)
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
        print(f"Patched Gradle SDK: {path}")
        return True
    return False

def append_property(path: Path, line: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    key = line.split("=", 1)[0]
    if key not in text:
        if text and not text.endswith("\n"):
            text += "\n"
        text += line + "\n"
        path.write_text(text, encoding="utf-8")
        print(f"Added property: {line} -> {path}")

def main() -> None:
    project = Path.cwd()

    # App Gradle files generated by flutter create.
    for p in [
        project / "android/app/build.gradle",
        project / "android/app/build.gradle.kts",
        project / "android/build.gradle",
        project / "android/build.gradle.kts",
    ]:
        patch_file(p)

    # Patch all Android plugin Gradle files in pub cache.
    # This fixes errors like:
    # file_picker is currently compiled against android-34
    # flutter_plugin_android_lifecycle requires Android API 36.
    home = Path.home()
    cache_roots = [
        home / ".pub-cache/hosted/pub.dev",
        project / ".pub-cache/hosted/pub.dev",
    ]

    patched = 0
    for root in cache_roots:
        if not root.exists():
            continue
        for p in root.glob("*/android/build.gradle*"):
            if patch_file(p):
                patched += 1

    # Also catch any plugin copies placed below the project.
    for p in project.glob("**/android/build.gradle*"):
        if ".gradle" in p.parts or "build" in p.parts:
            continue
        if patch_file(p):
            patched += 1

    # Gradle properties: suppress unsupported SDK warning and disable VFS watch issue.
    for props in [project / "android/gradle.properties", home / ".gradle/gradle.properties"]:
        append_property(props, f"android.suppressUnsupportedCompileSdk={ANDROID_API}")
        append_property(props, "org.gradle.vfs.watch=false")
        append_property(props, "org.gradle.daemon=false")

    print(f"Android compileSdk/targetSdk forced to {ANDROID_API}. Patched plugin files: {patched}")

if __name__ == "__main__":
    main()
